As an intern/rookie Data Analyst, you have just been handed this kaggle 2021 survey csv file, and asked to create a report in 30 minutes that outline the following:

1.   The number of programmers that use Python, SQL, and R
2.   The percentage of each category
3.   Statistics that show the maximum, minimum, and average compensation and years of experience in coding
4.   A relationship between experience and compensation.


-You have 30 minutes to do this (Impromptu, that's what we are trying to achieve)

-Feel free to experiment with shortcuts that work for you.

In [1]:
import pandas as pd

In [2]:
kaggle = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/python projects/kaggle_users_survey.csv')

In [3]:
kaggle

,experience_coding,python_user,r_user,sql_user,most_used,compensation
0,6.1,True,False,True,Scikit-learn,124267
1,12.3,True,True,True,Scikit-learn,236889
2,2.2,True,False,False,NaN,74321
3,2.7,False,False,True,NaN,62593
4,1.2,True,False,False,Scikit-learn,36288
...,...,...,...,...,...,...
25968,1.9,True,False,True,Scikit-learn,15800
25969,1.4,True,False,False,PyTorch,62456
25970,0.0,False,False,False,NaN,923
25971,9.4,True,False,True,Scikit-learn,60609
25972,0.0,False,False,False,NaN,493

First step is to understand the task at hand. What kind of report have yoiu been asked to create? What variables in this dataset can help you accomplish that?

Next, understand the distribution of the dataset; check that there are no missing values.

Although there are missing values in the 'most_used' column, it would not necessarily affect the analysis you are currently tasked with. (What are your thoughts?)

In [4]:
kaggle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25973 entries, 0 to 25972
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   experience_coding  25973 non-null  float64
 1   python_user        25973 non-null  bool
 2   r_user             25973 non-null  bool
 3   sql_user           25973 non-null  bool
 4   most_used          16835 non-null  object
 5   compensation       25973 non-null  int64
dtypes: bool(3), float64(1), int64(1), object(1)
memory usage: 685.0+ KB

## ***Check the number of programmers and their percentage distribution***

In [5]:
number_of_python_users = 0
number_of_r_users = 0
number_of_sql_users = 0

for x in kaggle.index:
  if kaggle.loc[x, 'python_user'] == True:
    number_of_python_users += 1

  if kaggle.loc[x, 'r_user'] == True:
    number_of_r_users += 1

  if kaggle.loc[x, 'sql_user'] == True:
    number_of_sql_users += 1

In [6]:
print(f'Python Users = {number_of_python_users}')
print(f'R Users = {number_of_r_users}')
print(f'SQL Users = {number_of_sql_users}')

print(f'Percentage of Python Users is {((number_of_python_users/len(kaggle))*100):.2f}%')
print(f'Percentage of R Users is {((number_of_r_users/len(kaggle))*100):.2f}%')
print(f'Percentage of SQL Users is {((number_of_sql_users/len(kaggle))*100):.2f}%')

Python Users = 21860
R Users = 5335
SQL Users = 10757
Percentage of Python Users is 84.16%
Percentage of R Users is 20.54%
Percentage of SQL Users is 41.42%

## ***Check the minimum, maximum and average years of experience and coding***

Don't forget to round off your numbers to avoid long trails

In [7]:
min_experience = kaggle['experience_coding'].min()
max_experience = kaggle['experience_coding'].max()
avg_experience = kaggle['experience_coding'].mean()

print(f'The minimum, maximum, and average years of experience are {min_experience, max_experience, round(avg_experience, 3)} respectively.')

The minimum, maximum, and average years of experience are (0.0, 30.0, 5.297) respectively.

In [8]:
min_compensation = kaggle['compensation'].min()
max_compensation = kaggle['compensation'].max()
avg_compensation = kaggle['compensation'].mean()

print(f'The minimum, maximum, and average compensation are {min_compensation, max_compensation, round(avg_compensation, 2)} respectively.')

The minimum, maximum, and average compensation are (0, 1492951, 53252.82) respectively.

## ***Categorize the compensation based on the years of coding experience***

You can choose to categorise in 10s or 2s; I used 5s.

Based on that, calculate the number of programmers in each category, and the average compensation in $.

In [9]:
lessthan_5yrs_exp = []
_5to10yrs_exp =  []
_10to15yrs_exp = []
_15to20yrs_exp = []
_20to25yrs_exp = []
morethan_25yrs_exp = []

In [10]:
for index, rows in kaggle.iterrows():
  exp = rows['experience_coding']
  comp = rows['compensation']

  if exp < 5:
   lessthan_5yrs_exp.append(comp)

  if exp >= 5 and exp < 10:
   _5to10yrs_exp.append(comp)

  if exp >= 10 and exp < 15:
   _10to15yrs_exp.append(comp)

  if exp >= 15 and exp < 20:
   _15to20yrs_exp.append(comp)

  if exp >=20 and exp < 25:
   _20to25yrs_exp.append(comp)

  if exp >= 25:
   morethan_25yrs_exp.append(comp)

In [11]:
print(f'Programmers with less than 5 years experience are {len(lessthan_5yrs_exp)}, with average compensation ${round(sum(lessthan_5yrs_exp)/len(lessthan_5yrs_exp), 2)}')
print(f'Programmers with 5 to 10 years experience are {len(_5to10yrs_exp)}, with average compensation ${round(sum(_5to10yrs_exp)/len(_5to10yrs_exp), 2)}')
print(f'Programmers with 15 to 20 years experience are {len(_15to20yrs_exp)}, with average compensation ${round(sum(_15to20yrs_exp)/len(_15to20yrs_exp), 2)}')
print(f'Programmers with 20 to 25 years experience are {len(_20to25yrs_exp)}, with average compensation ${round(sum(_20to25yrs_exp)/len(_20to25yrs_exp), 2)}')
print(f'Programmers with more than 25 years experience are {len(morethan_25yrs_exp)}, with average compensation ${round(sum(morethan_25yrs_exp)/len(morethan_25yrs_exp), 2)}')

Programmers with less than 5 years experience are 18753, with average compensation $45047.87
Programmers with 5 to 10 years experience are 3167, with average compensation $59312.82
Programmers with 15 to 20 years experience are 1069, with average compensation $75101.83
Programmers with 20 to 25 years experience are 925, with average compensation $103159.8
Programmers with more than 25 years experience are 941, with average compensation $90444.99